#!/usr/bin/bash

active1="[1*]  2  3  4  5"
active2="1  [2*]  3  4  5"
active3="1  2  [3*]  4  5"
active4="1  2  3  [4*]  5"
active5="1  2  3  4  [5*]"

if [ $1 = 1 ]; then
	echo "$active1" > /home/ahmad/.config/hikari/act-work
elif [ $1 = 2 ]; then   
	echo "$active2" > /home/ahmad/.config/hikari/act-work
elif [ $1 = 3 ]; then   
	echo "$active3" > /home/ahmad/.config/hikari/act-work
elif [ $1 = 4 ]; then   
	echo "$active4" > /home/ahmad/.config/hikari/act-work
elif [ $1 = 5 ]; then   
	echo "$active5" > /home/ahmad/.config/hikari/act-work
fi
